Milestone: Project finished
lordksix/trial-review pull request #1
Opened 2023-03-24 01:12 UTC by lordksix

# Milestone: Project finished
In this milestone the project was finished:
- Added GitHub Actions to automate linter.
- Copied files from Project-3, **check README.md** for more details.

2023-03-24 01:31 UTC, lordksix commented
Hi @lordksix ,


Great job so far! 👏 
It shows that you worked really hard on this project, and you should be proud, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
- There are linter errors :pensive: 
_Check the comments under the review._

<img src="https://media.giphy.com/media/z5cNqbFbMTDA4/giphy.gif"/>


## Optional suggestions
_Check the comments under the review._

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 01:57 UTC, lordksix commented on index.html
> +          ></a>
Good job setting up live and useful links using <a> tag :+1: , however, whenever **target="_blank"** it is used, it is necessary to use **rel="noopener"**. More information can be found [here](https://webhint.io/docs/user-guide/hints/hint-disown-opener/). :eyeglasses:

2023-03-24 01:57 UTC, lordksix commented on styles.css
> +{
Awesome job! Very detailed stylesheet, however, There should always be a line between the end of the rule and the beginning of a new rule, and the opening bracket should always be on the same line as the opening of the rule

2023-03-24 01:57 UTC, lordksix commented on styles.css
> +.nav {
Awesome job! Very detailed stylesheet, however, There should always be a line between the end of the rule.

2023-03-24 01:57 UTC, lordksix commented on styles.css
> +  {
Awesome job! Very detailed stylesheet, however, the opening bracket should always be on the same line as the opening of the rule

2023-03-24 01:57 UTC, lordksix commented on styles.css
> +{
Awesome job! Very detailed stylesheet, however, the opening bracket should always be on the same line as the opening of the rule

2023-03-27 13:25 UTC, leonardodiasb requested changes
.

2023-03-27 13:31 UTC, leonardodiasb approved these changes
# Status: ✔️ Project Approved ✔️ 

Hi @lordksix,

Everything is looking great! Please, merge this branch :shipit:
Congratulations! 🎉

## Highlights

 - Very polite comments. ✔️
 - Great use of inline comments. ✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-27 13:43 UTC, merged